#!/bin/bash
printf "\033[1;32mHello {owner of namespace entity}. Can I have access to your namespace? My entity is $1 \033[0m\n"
printf "\033[1;34mHello! I'm granting you permissions on $NAMESPACE/* now \033[0m\n"
bw2 mkdot -f ns.ent -t myentity.ent -u $NAMESPACE/*

if [[ $? -eq 0 ]] ; then
    printf "\033[1;34mFinished! You can now pub/sub on $NAMESPACE/* \033[0m\n"
else
    printf "\033[1;31mSomething bad happened\033[0m\n"
fi
